version: '1.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-main
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 10s
      timeout: 5s
      retries: 3
  minio-client:
    image: minio/mc
    container_name: minio-client
    restart: always
    ports:
      - 9003:9003
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./bucket-init.sh:/bucket-init.sh
    entrypoint: ["/bin/sh", "/bucket-init.sh"]
    