version: '1.0'
services:
  minio:
    image: minio/minio:latest
    container_name: minio-main
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
  minio-client:
    image: minio/mc
    container_name: minio-client
    ports:
      - 9003:9003
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      ADDRESS: ${ADDRESS}
    depends_on:
      - minio
    volumes:
      - ./bucket-init.sh:/bucket-init.sh
    entrypoint: /bin/sh -c "sleep 5 && /bucket-init.sh"

    