version: '3.9'
services:
  ingest-daily:
    build:
      context: ./ingest/daily
      dockerfile: Dockerfile
      containerr_name: ingest-daily
      networks: 
        - db_default
  ingest-monthly:
    build:
      context: ./ingest/monthly
      dockerfile: Dockerfile
      container_name: ingest-monthly
      networks: 
        - db_default

