version: '3.9'
services:
  ingest-daily:
    build:
      context: .
      dockerfile: ingestion/daily/Dockerfile
    container_name: ingest-daily
    env_file:
      - ./shared/main.env
    networks: 
      - db_default
  ingest-monthly:
    build:
      context: .
      dockerfile: ingestion/monthly/Dockerfile
    container_name: ingest-monthly
    env_file:
      - ./shared/main.env
    networks: 
      - db_default       
networks:
  db_default:
    external: true

