version: '1.0'
services:
  postgresql:
    image: postgres:14.15
    container_name: postgres1
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB} #calling this var could be why create db sql was failing
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}


        

